name: Github Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create database
        run: |
            sqlite3 database.db < setup.sql

      - name: Fetch Repositories
        run: |
            gh repo list ${{ github.repository_owner }} --limit 1000 --source --public --json description,homepageUrl,id,languages,description,repositoryTopics,name,primaryLanguage,repositoryTopics,url  > repos.json
        env:
            GH_TOKEN: ${{ github.token }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1


      - name: test
        run: bun seed_db.ts
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4