name: Github Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repositories
        run: |
            gh repo list ${{ github.repository_owner }} --public --json description,homepageUrl,id,labels,languages,name,nameWithOwner,openGraphImageUrl,owner,primaryLanguage,repositoryTopics,url,  > repos.json
        env:
            GH_TOKEN: ${{ github.token }}
          

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4